### ISSUE TITLE
Using multiple threads for index creation

### ISSUE THREAD

**Issue by dselivanov** [jlmelville/rcpphnsw#11]
`hnswlib` says that:

> Thread-safe with other `add_items` calls, but not with `knn_query`

Which means [this for loop](https://github.com/jlmelville/rcpphnsw/blob/9d608fb69aabaa0f87e124feab02e5945fe69a1e/src/hnsw.cpp#L115) should be quite trivial to wrap into threaded loop.

I will send PR implementing this with OpenMP.

**Comment by SamGG** [comment]
Improving the index creation is the most interesting point in my application. On my machine, Python times are 13 sec for creation, 5 sec for querying 30 NN.

**Comment by dselivanov** [comment]
Query also can be threaded.

**Comment by jlmelville** [comment]
CRAN release (0.3.0) now has multi-threading support. I'll revisit the use of OpenMP in the future if necessary. Thanks to everyone for the contributions and discussion.
