### ISSUE TITLE
Package fails to load: cannot allocate vector of size 707042.2 Gb 

### ISSUE THREAD

**Issue by pdworzynski** [jlmelville/rcpphnsw#14]
Hi,

We encountered an issue when installing rcpphnsw from CRAN (ver 0.3.0) R 4.0.3. When loaded via `library("RcppHNSW")` the library thrown an error:
```
Error: package or namespace load failed for ‘RcppHNSW’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package RcppHNSW: Rcpp::loadModule(module = "HnswL2", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "HnswL2": cannot allocate vector of size 707042.2 Gb
```
The attempt to allocate such a large amount of memory could have to do with the fact that the server we compiled and run it on has 80 CPU cores and 2TB of RAM. The problem doesn't seem to occur on R 3.6.1. I tried looking through the code but couldn't find an obvious spot where the issue might lie. 

Thanks for any help!

**Comment by jlmelville** [comment]
Are you using Anaconda? This seems very similar to e.g. <https://github.com/eddelbuettel/rcppannoy/issues/47>.

**Comment by pdworzynski** [comment]
Yes, I am installing it within an anaconda environment which, according to the issue you posted, is likely the culprit. 
Thanks a lot!
