### ISSUE TITLE
over two batches resizeIndex

### ISSUE THREAD

**Issue by yuhanH** [jlmelville/rcpphnsw#15]
Hi. Very nice package to support find neighbors by batches.  I have one question about `resizeIndex`. 
In your example, after you `addItems` for the first batch, you `resizeIndex` of `p` to the number of all elements. 
```
# Increase the total capacity, so that it will handle the new data
p$resizeIndex(num_elements)
```
I am wondering if I have three batches. After `addItems` of the first batch, shall I `resizeIndex` of `p` to the number of first + second batches or all three batches?
Generally, I am wondering if we should  `resizeIndex` after each batch `addItems`.  Thanks.

**Comment by jlmelville** [comment]
Apologies for the exceptionally late reply to this issue. Either the notification went astray or I missed it.

The size of the HNSW index is supposed to be specified when it is created. So if you know the maximum number of items that will be added to the index, you don't need to ever call `resizeIndex`.

If you have an existing index that is already at its maximum capacity then calling `resizeIndex` is needed to create more space.

So if you create an index with enough space for 20 items:

```R
dim <- 16
num_elements <- 20
M <- 16
ef <- 10
p <- new(HnswL2, dim, num_elements, M, ef)
```

and you want to add the items in two batches of 10, e.g.

```R
p$addItems(data[1:10, ])
p$addItems(data[11:20, ])
```

you *don't* need to call `resizeIndex` in between the calls to `addItems`.

I suspect this information is no longer timely however. Sorry!

**Comment by yuhanH** [comment]
Thanks for your explanation!
