### ISSUE TITLE
`nmslib.DataType.SPARSE_VECTOR` type

### ISSUE THREAD

**Issue by BERENZ** [jlmelville/rcpphnsw#22]
Thanks for the great package! I have a question about sparse matrix (vector) support, which the `RcppHNSW` package does not support, unlike the `rnndescent` package.

I have seen that the `hnslib` library supports sparse vectors as demonstrated [here](https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_sparse_cosine.ipynb).  Do you plan to include the `nmslib.DataType.SPARSE_VECTOR` type? It will be super useful, as converting sparse to dense matrices is a bottleneck in most cases.

**Comment by jlmelville** [comment]
Thank you for the kind comments. Your linked notebook goes to the <https://github.com/nmslib/nmslib> project, which is a much more full-featured library than <https://github.com/nmslib/hnswlib>. This package only wraps `hnswlib`, so unless that library gains sparse vector support it doesn't seem possible for `RcppHNSW` to implement it.

**Comment by BERENZ** [comment]
You are absolutely right! I mistakenly took `nmslib` for `hnswlib` which does not support sparse vectors.
