### ISSUE TITLE
Speed vs Python implementation

### ISSUE THREAD

**Issue by SamGG** [jlmelville/rcpphnsw#9]
Hi,

I am a big fan of your work and I really appreciate your port of HNSW to R. I am working on Windows and I heartly think that R ecosystem is the top. Yesterday, I installed Python and did a comparison concerning HNSW library. I felt quite puzzled. I did a kNN search on a dataset of 300k points, 11 dimensions and looked for the 30 NN. It took 83 sec using RcppHNSW. Keeping every parameter identical (efConstruction, efSearch, M, as far I know), the computation took 60 sec with Python, using 1 thread, and 15 sec without any core specification, which corresponds of using all 4 cores of my laptop. I do understand that multi-threading leads in a gain of 4 x. Any idea about the overhead of 23 sec when using 1 core?

Best.

**Comment by LTLA** [comment]
I would guess that it all comes down to the compilation settings. In particular, **RcppHNSW** turns off the vectorization as it may not be generally supported across CPUs. 

(I don't know how true that is, but the main point is that some people compile with `-mtune=native` and others compile with `-mtune=generic` and we didn't want differences in behavior due to the compilation settings. While small, the differences are annoying if you're claiming reproducibility.)

Check out the `Makevars` and see if activating vectorization changes anything.

**Comment by SamGG** [comment]
Thanks for your answer Aaron. Vectorization did no clear difference.
I was not precise enough. In fact, I am using the hnsw_knn function, and not the low level functions. The problem I found is that the progress bar is CPU intensive. When turning verbose off, computation time fall down to 73 sec. I gained 10 sec by avoiding the R loop needed by the bar. 3 sec could be gained setting `arch=native`, but that's not really useful anymore. In the end, performance is similar to Python using 1 core. Multi-core would be the next gain.
I sent a PR. All results below made with the PR, which has no impact when verbose in TRUE.
```
# Using matrix import instead of the R loop
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = FALSE)
+ )
   user  system elapsed 
  63.36    0.05   63.41 

# When verbose, the progress bar is CPU intensive
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = TRUE)
+ )
00:23:44 Building HNSW index with metric 'euclidean' ef = 200 M = 16
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
00:24:59 Searching HNSW index with ef = 30
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
   user  system elapsed 
 105.14    0.09  105.31 

# -march=native
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = FALSE)
+ )
   user  system elapsed 
  60.78    0.07   60.89 
```

**Comment by jlmelville** [comment]
Thanks for the report (and PR) @SamGG. There seems to be some noticeable overhead to just the method dispatch, so I will see if swapping to a non-class-based approach for the progress bar helps for the `verbose = TRUE` case.

Or I might just rewrite the progress bar code entirely. Pretty ridiculous for it to affect the runtime like that.

**Comment by SamGG** [comment]
Thanks for your feedback.
If you rewrite that part, maybe I would like an intermediate verbose mode in which tsmessage reports start and finish, but the progress bar does not appear.
To be honest, I would prefer that your genius brain encodes the ParallelFor used in the Python library in order to take benefit of multi-threading. :-)
https://github.com/nmslib/hnswlib/blob/master/python_bindings/bindings.cpp

**Comment by dselivanov** [comment]
> To be honest, I would prefer that your genius brain encodes the ParallelFor used in the Python library in order to take benefit of multi-threading. :-)

Wouldn't it be better just use openmp?

**Comment by SamGG** [comment]
If it's possible, I agree. I spent a few minutes at that, but the task is not straightforward.

**Comment by jlmelville** [comment]
I have never actually used openmp. The linked to code seems like you can just use `std::thread` and chop the work up in chunks directly. For index searching, it seems straightforward (no genius required thankfully). I would need to take a long look at the index creation code, though. Even if it's thread-safe in terms of not causing horrible memory errors, I find it hard to believe that you can write to the index concurrently from multiple threads and get consistent results.

Unfortunately I don't have a lot of spare time for this at the moment and I would like to get the nearest neighbor descent implementation I am working on into shape before switching gears.

In the short term I will fix the progress bar problem at the very least, and also rev the current version of HNSW. There was a flurry of activity a little while ago but it seems to have gone a bit quiet so it's probably a good time to sync it back up.

**Comment by SamGG** [comment]
Concurrent index creation surprised me also. 
Thanks for the feedback and sharing your roadmap.

**Comment by SamGG** [comment]
@jlmelville Simple suggestion: I think that the most efficient way is to split the dataset into 50 chunks and to build a loop for import or search functions. I can do it if you agree.

**Comment by jlmelville** [comment]
@SamGG: I have replaced the old progress RC class with an imperative/function-based approach. 

I used the following dummy data:

```R
d300k <- data.frame(matrix(rnorm(n = 300000 * 11), ncol = 11))
```

Timing with the old progress bar:

```R
> system.time(d300k_hnsw <- hnsw_knn(as.matrix(d300k), k = 30, verbose = TRUE))
20:54:06 Building HNSW index with metric 'euclidean' ef = 200 M = 16
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:00:56 Finished building index
21:00:56 Searching HNSW index with ef = 30
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:02:04 Finished searching
   user  system elapsed 
 428.51   49.79  478.52 
```

New progress bar:

```R
system.time(d300k_hnsw <- hnsw_knn(as.matrix(d300k), k = 30, verbose = TRUE))
21:38:38 Building HNSW index with metric 'euclidean' ef = 200 M = 16
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:45:16 Finished building index
21:45:16 Searching HNSW index with ef = 30
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:46:13 Finished searching
   user  system elapsed 
 404.04   51.73  455.89 
```

With `verbose = FALSE`:

```R
system.time(d300k_hnsw <- hnsw_knn(as.matrix(d300k), k = 30, verbose = FALSE))
   user  system elapsed 
 396.99   49.80  447.00 
```

Now the computational overhead of the progress bar is much smaller (~2% of the runtime)

There is also a new `progress` option that you can set to `NULL` and you will get a few messages with `verbose = TRUE`, but no progress bar and no meaningful loss of speed:

```R
> system.time(d300k_hnsw <- hnsw_knn(as.matrix(d300k), k = 30, verbose = TRUE, progress = NULL))
21:53:42 Building HNSW index with metric 'euclidean' ef = 200 M = 16
22:00:15 Finished building index
22:00:15 Searching HNSW index with ef = 30
22:01:09 Finished searching
   user  system elapsed 
 397.29   49.71  447.16 
```

For parallel support, let's take it to a separate issue. Rather than specifying a fixed number of chunks, my preferred approach would be for the user to specify the number of threads and for the available work to be divided into that number of chunks, (and also subject to a grain_size parameter to prevent too many threads being created for smaller jobs).

**Comment by SamGG** [comment]
Waouh! Super! Perfect.
The chunks notice was about the progress bar (5 '*' for 10% progress), not for parallelization, for which I am a beginner.

**Comment by SamGG** [comment]
There is still a noticeable overhead between the new version and my PR in my hands (Windows10x64). Data available at https://drive.google.com/file/d/1MgnnY21Bgcw4W1Doa799-OBD4w7VjocY
```
# your latest github version
> library(RcppHNSW)
> set.seed(0)
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = FALSE)
+ )
   user  system elapsed 
  73.94    0.01   74.32 

# my PR
> flow18_300k <- as.matrix(flow18_300k)
> 
> set.seed(0)
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = FALSE)
+ )
   user  system elapsed 
  63.95    0.09   64.17 
```

**Comment by jlmelville** [comment]
Sorry @SamGG, I have now properly integrated your PR into the codebase, although I didn't merge it directly as I had messed about with the innards of the code sufficiently by the time I realized my mistake. You have been added as a contributor to the `DESCRIPTION`, hope that's ok. And thank you for providing the data.

The non-progress-bar code path should now be as fast as your PR. The progress-bar code path should be within a few percent, as I finally understood and took your advice on breaking the input data into 50 chunks. A side-effect of this is that no progress bar will appear with less than 50 items.

Timings on my machine:

```R
> system.time(flow18_300k_hnsw <- hnsw_knn(as.matrix(flow18_300k), k = 30, verbose = TRUE))
# progress bar output elided
   user  system elapsed 
 318.23   49.22  370.73 
> system.time(flow18_300k_hnsw <- hnsw_knn(as.matrix(flow18_300k), k = 30, verbose = FALSE))
   user  system elapsed 
 315.72   48.87  365.38 
> system.time(flow18_300k_hnsw <- hnsw_knn(as.matrix(flow18_300k), k = 30, verbose = TRUE, progress = NULL))
# log messages elided
   user  system elapsed 
 319.01   48.87  369.94 
```

**Comment by SamGG** [comment]
Thanks for the new code. It works perfectly. The overload is 1% in my case, that's very good. I'm sorry to have bothered you. Thank you for notifying me of my small contribution. And thank you all your tests on dimension reductions.
```
> set.seed(0)
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = FALSE)
+ )
   user  system elapsed 
  63.51    0.12   63.74 
> set.seed(0)
> system.time(
+   knn <- RcppHNSW::hnsw_knn(flow18_300k, k = 30, verbose = TRUE)
+ )
11:32:12 Building HNSW index with metric 'euclidean' ef = 200 M = 16
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:33:05 Finished building index
11:33:05 Searching HNSW index with ef = 30
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:33:17 Finished searching
   user  system elapsed 
  64.28    0.12   64.54 
```
